import JSZip from "jszip";
export const getDeploymentFiles = (project) => {
  return [
    {
      name: "index.html",
      type: "page",
    },
    {
      name: "robots.txt",
      type: "seo",
    },
    {
      name: "sitemap.xml",
      type: "seo",
    },
    {
      name: "manifest.json",
      type: "pwa",
    },
    {
      name: "README.txt",
      type: "guide",
    },
  ];
};

export const buildDeploymentSummary = (project) => {
  return {
    businessName: project?.businessName || "",
    domain: project?.domain || "",
    generatedAt: new Date().toISOString(),
    files: getDeploymentFiles(project),
  };
};
export const generateReadme = (project) => {
  return `
========================================
RETIVIO WEBSITE DEPLOYMENT PACKAGE
========================================

Business:
${project?.businessName || "Business"}

Domain:
${project?.domain || "Not configured"}

Hosting Provider:
${project?.hostingProvider || "Not selected"}

========================================
DEPLOYMENT STEPS
========================================

1. Login to your hosting account.

2. Open File Manager.

3. Upload website.zip.

4. Extract into public_html.

5. Point your domain.

6. Enable SSL.

7. Visit your website.

========================================
Generated by Retivio
========================================
`;
};

export const generateManifestJson = (project) => {
  return JSON.stringify(
    {
      name: project?.businessName || "Retivio Website",
      short_name: project?.businessName || "Retivio",
      start_url: "/",
      display: "standalone",
      background_color: "#0f172a",
      theme_color: "#7c3aed",
      icons: [
        {
          src: "/favicon.ico",
          sizes: "64x64",
          type: "image/x-icon",
        },
      ],
    },
    null,
    2
  );
};

export const generateStyleCss = (project) => {
  const color =
    project?.formData?.primaryColor || "#7e22ce";

  return `
*{
margin:0;
padding:0;
box-sizing:border-box;
}

body{
font-family:Arial,sans-serif;
background:#ffffff;
color:#111827;
line-height:1.7;
}

header{
background:${color};
color:white;
padding:60px 20px;
text-align:center;
}

main{
max-width:1100px;
margin:auto;
padding:40px 20px;
}

section{
margin-bottom:60px;
}

h1,h2,h3{
margin-bottom:15px;
}

footer{
background:#111827;
color:white;
padding:40px;
text-align:center;
}
`;
};

export const generateAssetsManifest = (project) => {
  return {
    heroImage: project?.websiteMedia?.hero || null,
    aboutImage: project?.websiteMedia?.about || null,
    gallery: project?.websiteMedia?.gallery || [],
  };
};

export const generateDeploymentBundle = (project) => {
  return {
"index.html": generateIndexHtml(project),  
"assets/style.css": generateStyleCss(project), 
 "README.txt": generateReadme(project),
    "robots.txt": generateRobotsTxt(project?.domain),
    "sitemap.xml": generateSitemapXml(project?.domain),
    "manifest.json": generateManifestJson(project),  
"assets/assets.json": JSON.stringify(
  generateAssetsManifest(project),
  null,
  2
),
};
};

export const generateRobotsTxt = (domain) => {
  const host = domain?.trim()
    ? `https://${domain.trim()}`
    : "https://example.com";

  return `User-agent: *

Allow: /

Sitemap: ${host}/sitemap.xml
`;
};

export const generateSitemapXml = (domain) => {
  const host = domain?.trim()
    ? `https://${domain.trim()}`
    : "https://example.com";

  return `<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

<url>
<loc>${host}</loc>
<priority>1.0</priority>
</url>

</urlset>`;
};

export const createDeploymentZip = async (project) => {
  const zip = new JSZip();

  const bundle = generateDeploymentBundle(project);

  Object.entries(bundle).forEach(([fileName, content]) => {
    zip.file(fileName, content);
  });

  return await zip.generateAsync({
    type: "blob",
  });
};

export const generateIndexHtml = (project) => {
const formData = project?.formData || {};

const businessName =
  formData.businessName || "Your Business";

const tagline =
  formData.tagline || "";

const about =
  formData.about || "";

const phone =
  formData.phone || "";

const address =
  formData.address || "";

const primaryColor =
  formData.primaryColor || "#7e22ce";

const services = project?.services || [];

const servicesHtml = services
  .map(
    (service) => `
<div style="
border:1px solid #e5e7eb;
border-radius:12px;
padding:20px;
margin-top:20px;
">
<h3>${service.name}</h3>

<p>${service.description || ""}</p>
</div>
`
  )
  .join("");

const gallery = project?.websiteMedia?.gallery || [];

const galleryHtml = gallery
  .map(
    (image) => `
<div style="
width:220px;
height:220px;
border-radius:12px;
overflow:hidden;
border:1px solid #ddd;
display:flex;
align-items:center;
justify-content:center;
background:#f8fafc;
">
<img
src="${image?.url || image}"
style="width:100%;height:100%;object-fit:cover;"
/>
</div>
`
  )
  .join("");

const blogPosts = project?.blogPosts || [];

const blogHtml = blogPosts
  .map(
    (post) => `
<article style="
border:1px solid #e5e7eb;
padding:20px;
border-radius:12px;
margin-top:20px;
">
<h3>${post.title || ""}</h3>

<p>${post.excerpt || ""}</p>

</article>
`
  )
  .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${businessName}</title>
<meta name="theme-color" content="${primaryColor}">
<meta name="description" content="Website generated by Retivio">
<link rel="manifest" href="manifest.json">
<link rel="stylesheet" href="assets/style.css">
</head>

<body>

<header style="padding:60px 20px;text-align:center;background:${primaryColor};color:white;">
  <h1>${businessName}</h1>

  <p>${tagline}</p>
</header>

<main style="max-width:1100px;margin:auto;padding:40px;">

<section>
<h2>About</h2>

<p>${about}</p>
</section>

<section style="margin-top:40px;">

<h2>Contact</h2>

<p>Phone: ${phone}</p>

<p>Address: ${address}</p>

</section>

<section style="margin-top:50px;">

<h2>Our Services</h2>

${servicesHtml}

</section>

<section style="margin-top:60px;">

<h2>Gallery</h2>

<div
style="
display:flex;
flex-wrap:wrap;
gap:20px;
margin-top:20px;
"
>

${galleryHtml}

</div>

</section>

<section style="margin-top:60px;">

<h2>Latest Articles</h2>

${blogHtml}

</section>

</main>

<footer
style="
margin-top:80px;
padding:40px;
background:#111827;
color:white;
text-align:center;
"
>

<h3>${businessName}</h3>

<p>${address}</p>

<p>${phone}</p>

<p style="margin-top:20px;">
© ${new Date().getFullYear()} ${businessName}
</p>

<p style="font-size:12px;opacity:.7;">
Generated by Retivio Website Builder
</p>

</footer>

</body>
</html>`;
};
