import JSZip from "jszip";
export const getDeploymentFiles = (project) => {
  return [
    {
      name: "index.html",
      type: "page",
    },
    {
      name: "robots.txt",
      type: "seo",
    },
    {
      name: "sitemap.xml",
      type: "seo",
    },
    {
      name: "manifest.json",
      type: "pwa",
    },
    {
      name: "README.txt",
      type: "guide",
    },
  ];
};

export const buildDeploymentSummary = (project) => {
  return {
    businessName: project?.businessName || "",
    domain: project?.domain || "",
    generatedAt: new Date().toISOString(),
    files: getDeploymentFiles(project),
  };
};
export const generateReadme = (project) => {
  return `
========================================
RETIVIO WEBSITE DEPLOYMENT PACKAGE
========================================

Business:
${project?.businessName || "Business"}

Domain:
${project?.domain || "Not configured"}

Hosting Provider:
${project?.hostingProvider || "Not selected"}

========================================
DEPLOYMENT STEPS
========================================

1. Login to your hosting account.

2. Open File Manager.

3. Upload website.zip.

4. Extract into public_html.

5. Point your domain.

6. Enable SSL.

7. Visit your website.

========================================
Generated by Retivio
========================================
`;
};

export const generateManifestJson = (project) => {
  return JSON.stringify(
    {
      name: project?.businessName || "Retivio Website",
      short_name: project?.businessName || "Retivio",
      start_url: "/",
      display: "standalone",
      background_color: "#0f172a",
      theme_color: "#7c3aed",
      icons: [
        {
          src: "/favicon.ico",
          sizes: "64x64",
          type: "image/x-icon",
        },
      ],
    },
    null,
    2
  );
};

export const generateStyleCss = (project) => {
  const color =
    project?.formData?.primaryColor || "#7e22ce";

  return `
*{
margin:0;
padding:0;
box-sizing:border-box;
}

body{
font-family:Arial,sans-serif;
background:#ffffff;
color:#111827;
line-height:1.7;
}

header{
background:${color};
color:white;
padding:60px 20px;
text-align:center;
}

main{
max-width:1100px;
margin:auto;
padding:40px 20px;
}

section{
margin-bottom:60px;
}

h1,h2,h3{
margin-bottom:15px;
}

footer{
background:#111827;
color:white;
padding:40px;
text-align:center;
}
`;
};

export const generateAssetsManifest = (project) => {
  return {
    heroImage: project?.websiteMedia?.hero || null,
    aboutImage: project?.websiteMedia?.about || null,
    gallery: project?.websiteMedia?.gallery || [],
  };
};

export const generateDeploymentBundle = (project) => {
  return {
"index.html": generateIndexHtml(project),  
"assets/style.css": generateStyleCss(project), 
 "README.txt": generateReadme(project),
    "robots.txt": generateRobotsTxt(project?.domain),
    "sitemap.xml": generateSitemapXml(project?.domain),
    "manifest.json": generateManifestJson(project),  
"assets/assets.json": JSON.stringify(
  generateAssetsManifest(project),
  null,
  2
),
};
};

export const generateRobotsTxt = (domain) => {
  const host = domain?.trim()
    ? `https://${domain.trim()}`
    : "https://example.com";

  return `User-agent: *

Allow: /

Sitemap: ${host}/sitemap.xml
`;
};

export const generateSitemapXml = (domain) => {
  const host = domain?.trim()
    ? `https://${domain.trim()}`
    : "https://example.com";

  return `<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

<url>
<loc>${host}</loc>
<priority>1.0</priority>
</url>

</urlset>`;
};

export const createDeploymentZip = async (project) => {
 
console.log("=== EXPORT DEBUG ===");
console.log(project?.websiteMedia);
console.log(project?.formData);
console.log("====================");
 const zip = new JSZip();

  const bundle = generateDeploymentBundle(project);

  Object.entries(bundle).forEach(([fileName, content]) => {
    zip.file(fileName, content);
  });
const heroUrl = project?.websiteMedia?.hero?.url;

if (heroUrl) {
  try {
    const response = await fetch(heroUrl);

    if (response.ok) {
      const blob = await response.blob();

      const extension =
        heroUrl.split(".").pop().split("?")[0] || "jpg";

      zip.file(
        `assets/images/hero.${extension}`,
        blob
      );
    }
  } catch (error) {
    console.error("Hero image export failed:", error);
  }
}
const aboutUrl = project?.websiteMedia?.about?.url;

if (aboutUrl) {
  try {
    const response = await fetch(aboutUrl);

    if (response.ok) {
      const blob = await response.blob();

      const extension =
        aboutUrl.split(".").pop().split("?")[0] || "jpg";

      zip.file(
        `assets/images/about.${extension}`,
        blob
      );
    }
  } catch (error) {
    console.error("About image export failed:", error);
  }
}
const gallery = project?.websiteMedia?.gallery || [];

for (let i = 0; i < gallery.length; i++) {
  const imageUrl = gallery[i]?.url;

  if (!imageUrl) continue;

  try {
    const response = await fetch(imageUrl);

    if (response.ok) {
      const blob = await response.blob();

      const extension =
        imageUrl.split(".").pop().split("?")[0] || "jpg";

      zip.file(
        `assets/images/gallery-${i + 1}.${extension}`,
        blob
      );
    }
  } catch (error) {
    console.error(
      `Gallery image ${i + 1} export failed:`,
      error
    );
  }
}

return await zip.generateAsync({
  type: "blob",
  compression: "DEFLATE",
});
};

export const generateIndexHtml = (project) => {
const formData = project?.formData || {};

const businessName =
  formData.businessName || "Your Business";

const tagline =
  formData.tagline || "";

const about =
  formData.about || "";

const phone =
  formData.phone || "";

const address =
  formData.address || "";

const primaryColor =
  formData.primaryColor || "#7e22ce";

const services = project?.services || [];

const servicesHtml = services
  .map(
    (service) => `
<div style="
border:1px solid #e5e7eb;
border-radius:12px;
padding:20px;
margin-top:20px;
">
<h3>${service.name}</h3>

<p>${service.description || ""}</p>
</div>
`
  )
  .join("");

const heroImage = project?.websiteMedia?.hero?.url || "";

const aboutImage = project?.websiteMedia?.about?.url || "";

const gallery = project?.websiteMedia?.gallery || [];

const galleryHtml = gallery
  .map(
    (image, index) => `
<div style="
width:220px;
height:220px;
border-radius:12px;
overflow:hidden;
border:1px solid #ddd;
display:flex;
align-items:center;
justify-content:center;
background:#f8fafc;
">
<img
src="./assets/images/gallery-${index + 1}.webp"
style="width:100%;height:100%;object-fit:cover;"
/>
</div>
`
  )
  .join("");

const blogPosts = project?.blogPosts || [];

const blogHtml = blogPosts
  .map(
    (post) => `
<article style="
border:1px solid #e5e7eb;
padding:20px;
border-radius:12px;
margin-top:20px;
">
<h3>${post.title || ""}</h3>

<p>${post.excerpt || ""}</p>

</article>
`
  )
  .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${businessName}</title>
<meta name="theme-color" content="${primaryColor}">
<meta name="description" content="Website generated by Retivio">
<link rel="manifest" href="manifest.json">
<link rel="stylesheet" href="assets/style.css">
</head>

<body>

<header id="home"
style="
background:${primaryColor};
color:white;
text-align:center;
padding:0 0 60px;
"
>

<nav
style="
display:flex;
justify-content:center;
gap:24px;
padding:18px;
background:rgba(255,255,255,.08);
backdrop-filter:blur(8px);
flex-wrap:wrap;
"
>

<a href="#home" style="color:white;text-decoration:none;font-weight:600;">Home</a>

<a href="#about" style="color:white;text-decoration:none;font-weight:600;">About</a>

<a href="#services" style="color:white;text-decoration:none;font-weight:600;">Services</a>

<a href="#gallery" style="color:white;text-decoration:none;font-weight:600;">Gallery</a>

<a href="#blog" style="color:white;text-decoration:none;font-weight:600;">Blog</a>

<a href="#contact" style="color:white;text-decoration:none;font-weight:600;">Contact</a>

</nav>
${heroImage ? `
<img
src="./assets/images/hero.webp"
alt="${businessName}"
style="
width:100%;
max-height:480px;
object-fit:cover;
display:block;
margin-bottom:40px;
"
/>
` : ""}

<div style="padding:0 20px;">

<h1>${businessName}</h1>

<p>${tagline}</p>

<a
href="#contact"
style="
display:inline-block;
margin-top:25px;
padding:14px 28px;
background:white;
color:${primaryColor};
text-decoration:none;
font-weight:bold;
border-radius:999px;
"
>
Book Now
</a>

</div>

</header>
<main style="max-width:1100px;margin:auto;padding:40px;">

<section id="about">
<h2>About</h2>
<div
style="
display:flex;
flex-wrap:wrap;
gap:40px;
align-items:center;
margin-top:20px;
"
>

<div style="flex:1;min-width:280px;">
<p>${about}</p>
</div>

${
  aboutImage
    ? `
<div style="flex:1;min-width:280px;">
<img
src="./assets/images/about.webp"
alt="${businessName} about"
style="
width:100%;
border-radius:16px;
display:block;
"
/>
</div>
`
    : ""
}

</div>
</section>

<section id="contact" style="margin-top:40px;">

<h2>Contact</h2>

<div
style="
display:grid;
grid-template-columns:repeat(auto-fit,minmax(240px,1fr));
gap:20px;
margin-top:25px;
"
>

<div style="padding:20px;border:1px solid #e5e7eb;border-radius:14px;">
<h3>📞 Phone</h3>
<p>${phone || "Not Available"}</p>
</div>

<div style="padding:20px;border:1px solid #e5e7eb;border-radius:14px;">
<h3>📍 Address</h3>
<p>${address || "Not Available"}</p>
</div>

<div style="padding:20px;border:1px solid #e5e7eb;border-radius:14px;">
<h3>📧 Email</h3>
<p>${formData.email || "Not Available"}</p>
</div>

<div style="padding:20px;border:1px solid #e5e7eb;border-radius:14px;">
<h3>💬 WhatsApp</h3>
<p>${phone || "Not Available"}</p>
</div>

</div>

</section>

<section id="services" style="margin-top:50px;">

<h2>Our Services</h2>

${servicesHtml}

</section>

<section style="margin-top:60px;">

<h2>Gallery</h2>

<div
style="
display:flex;
flex-wrap:wrap;
gap:20px;
margin-top:20px;
"
>

${galleryHtml}

</div>

</section>

<section id="blog" style="margin-top:60px;">
<h2>Latest Articles</h2>

${blogHtml}

</section>

</main>

<footer
style="
margin-top:80px;
padding:50px 20px;
background:#111827;
color:white;
text-align:center;
"
>

<h3 style="margin-bottom:12px;">
${businessName}
</h3>

<p>${address}</p>

<p style="margin-top:8px;">
${phone}
</p>

<div style="margin:30px 0;">
<a href="privacy.html" style="color:white;margin:0 15px;text-decoration:none;">Privacy Policy</a>

<a href="terms.html" style="color:white;margin:0 15px;text-decoration:none;">Terms & Conditions</a>
</div>

<p style="opacity:.75;">
© ${new Date().getFullYear()} ${businessName}. All Rights Reserved.
</p>

<p style="margin-top:15px;font-size:13px;opacity:.65;">
Powered by Retivio Website Builder
</p>

</footer>

</body>
</html>`;
};
