export const getDeploymentFiles = (project) => {
  return [
    {
      name: "index.html",
      type: "page",
    },
    {
      name: "robots.txt",
      type: "seo",
    },
    {
      name: "sitemap.xml",
      type: "seo",
    },
    {
      name: "manifest.json",
      type: "pwa",
    },
    {
      name: "README.txt",
      type: "guide",
    },
  ];
};

export const buildDeploymentSummary = (project) => {
  return {
    businessName: project?.businessName || "",
    domain: project?.domain || "",
    generatedAt: new Date().toISOString(),
    files: getDeploymentFiles(project),
  };
};
export const generateReadme = (project) => {
  return `
========================================
RETIVIO WEBSITE DEPLOYMENT PACKAGE
========================================

Business:
${project?.businessName || "Business"}

Domain:
${project?.domain || "Not configured"}

Hosting Provider:
${project?.hostingProvider || "Not selected"}

========================================
DEPLOYMENT STEPS
========================================

1. Login to your hosting account.

2. Open File Manager.

3. Upload website.zip.

4. Extract into public_html.

5. Point your domain.

6. Enable SSL.

7. Visit your website.

========================================
Generated by Retivio
========================================
`;
};
